config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'statics#home'

  get "/presentation", to: "statics#presentation"
  get "/team", to: "statics#team"

  resources :partners, only: [:create, :update, :index, :destroy]
  resources :thanks, only: [:create, :update, :index, :destroy]
  resources :rallies, only: [:new, :edit, :update, :create, :show, :destroy] do
    resources :articles, only: [:create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :rally
  has_one_attached :image

  default_scope { order(created_at: :desc) }

  def to_react
    self.attributes.merge(
      image_url: self.image.attached? && Rails.application.routes.url_helpers.rails_blob_path(self.image, only_path: true),
      date: self.created_at.strftime("Publié le %d/%m/%Y"),
      )
  end
end

app/models/partner.rb
class Partner < ApplicationRecord
  default_scope { order(created_at: :desc) }

  has_one_attached :logo

  def to_react
    self.attributes.merge(
      logo_url: self.logo.attached? && Rails.application.routes.url_helpers.rails_blob_path(self.logo, only_path: true),
      )
  end
end

app/models/rally.rb
class Rally < ApplicationRecord
  default_scope { order(created_at: :desc) }

  has_many :articles
end

app/models/thank.rb
class Thank < ApplicationRecord
  default_scope { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_rallies

  def set_rallies
    @rallies = Rally.all
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ update destroy ]

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article.rally, notice: "L'article \"#{@article.title}\" a été créé."
    else
      render :new, alert: "Erreur lors de la mise à jour de l'article."
    end
  end

  def update
    if @article.update(article_params)
      @article.image.purge if params[:article][:delete_image] == "1"
      redirect_to @article.rally, notice: "L'article \"#{@article.title}\" a été mis à jour."
    else
      render :new, alert: "Erreur lors de la mise à jour de l'article."
    end
  end

  def destroy
    @article.destroy
    redirect_to @article.rally, notice: "L'article \"#{@article.title}\" a été effacé."
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :rally_id, :image)
    end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: %i[ edit update destroy ]

  def index
    @partners = Partner.all
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)

    if @partner.save
      redirect_to partners_path, notice: "Le partenaire \"#{@partner.name}\" a été ajouté."
    else
      render :new, alert: "Erreur lors de la création du partenaire."
    end
  end

  def update
    if @partner.update(partner_params)
      @partner.logo.purge if params[:partner][:delete_logo] == "1"
      redirect_to partners_path, notice: "Le partenaire \"#{@partner.name}\" a été mis à jour."
    else
      render :new, alert: "Erreur lors de la création du partenaire."
    end
  end

  def destroy
    @partner.destroy
    redirect_to partners_path, notice: "Le partenaire \"#{@partner.name}\" a été effacé."
  end

  private
    def set_partner
      @partner = Partner.find(params[:id])
    end

    def partner_params
      params.require(:partner).permit(:name, :description, :logo, :url)
    end
end

app/controllers/rallies_controller.rb
class RalliesController < ApplicationController
  before_action :set_rally, only: %i[ show update destroy ]

  def show
    @article = Article.new
  end

  def new
    @rally = Rally.new
  end

  def edit
  end

  def create
    @rally = Rally.new(rally_params)

    if @rally.save
      redirect_to @rally, notice: "Le rallye \"#{@rally.title}\" a été ajouté."
    else
      render :new, alert: "Erreur lors de la création du rally."
    end
  end

  def update
    if @rally.update(rally_params)
      redirect_to @rally, notice: "Le rallye \"#{@rally.title}\" a été édité."
    else
      render :new, alert: "Erreur lors de la mise à jour du rally."
    end
  end

  def destroy
    @rally.destroy
    redirect_to root_path, notice: "Le rally \"#{@rally.title}\" a été effacé."
  end

  private
    def set_rally
      @rally = Rally.find(params[:id])
    end

    def rally_params
      params.require(:rally).permit(:title, :presentation)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  before_action :set_thank, only: %i[ edit update destroy ]

  def index
    @thanks = Thank.all
  end

  def create
    @thank = Thank.new(thank_params)

    if @thank.save
      redirect_to thanks_path, notice: "Le remerciement \"#{@thank.id}\" a été ajouté."
    else
      render :new, alert: "Erreur lors de la création du remerciement."
    end
  end

  def update
    if @thank.update(thank_params)
      @thank.logo.purge if params[:thank][:delete_logo] == "1"
      redirect_to thanks_path, notice: "Le remerciement \"#{@thank.id}\" a été mis à jour."
    else
      render :new, alert: "Erreur lors de la création du remerciement."
    end
  end

  def destroy
    @thank.destroy
    redirect_to thanks_path, notice: "Le remerciement \"#{@thank.id}\" a été effacé."
  end

  private
    def set_thank
      @thank = Thank.find(params[:id])
    end

    def thank_params
      params.require(:thank).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/rallies_helper.rb
module RalliesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/articles/_form.html.haml
= form_with model: [rally, article] do |f|
  - if article.new_record?
    = f.hidden_field :rally_id, { value: rally.id }
  %label Titre
  = f.text_field :title, { class: "form-control mb-3", placeholder: "Titre..." }
  %label Image
  -if f.object.image.attached?
    = image_tag f.object.image, class: "img-fluid"
    .form-check.form-switch
    = f.check_box :delete_image, class: "form-check-input", id: "deleteImage"
    %label.form-check-label{:for => "deleteImage"} Effacer l'image?
  = f.file_field :image, { class: "form-control mb-3", accept: 'image/png,image/gif,image/jpeg' }
  %label Contenu
  = react_component("Ckeditor5", name: "article[content]", value: article.content)
  = f.submit article.new_record? ? "Créer un article" : "Editer l'article", { class: "btn btn-success mb-3 w-100"}

app/views/articles/_show.html.haml
.div.position-relative
  = react_component("Article", article: article.to_react)
  - if current_user
    %a.position-absolute.top-0.end-0.p-1{"data-bs-target" => "#article-#{article.id}", "data-bs-toggle" => "modal", :type => "button"}
      = fa_icon "edit 2x"
    .modal.fade{id: "article-#{article.id}", "aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-xl
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Edition de l'article
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            = render 'articles/form', article: article, rally: article.rally
            %button.w-100.ml-auto.btn.btn-warning.mb-3{"data-bs-target" => "#articleDelete-#{article.id}", "data-bs-toggle" => "modal", :type => "button"}
              Supprimer l'article
            %button.w-100.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Annuler
    .modal.fade{id: "articleDelete-#{article.id}", "aria-hidden" => "true", "aria-labelledby" => "editionModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-dialog-centered
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Suppression de l'article
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            %p.danger La suppression de l'article est irréversible, êtes-vous sûr de vouloir continuer?
          .modal-footer
            %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Annuler
            = link_to rally_article_path(article.rally, article), method: "DELETE" do
              %button.btn.btn-danger{:type => "button"} Effacer

app/views/layouts/_footer.html.haml
%footer{class: "mt-auto page-footer font-small blue pt-4 bg-light "}
  %div{class: "footer-copyright text-center py-4"}
    %p
      Association loi 1er juillet 1901 :
      %a{href: "/"} envoituresimone

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    = link_to root_path do
      = image_tag "envoituresimone-logo.png", style: "height: 70px", class: "mx-2"
    = link_to "EN VOITURE SIMONE", root_path, class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
            Rallyes
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            - @rallies.each do |rally|
              %li
                = link_to rally.title, rally_path(rally), class: "dropdown-item"
            - if current_user
              %li
                %hr.dropdown-divider
              %li
                = link_to "Rajouter un rallye", new_rally_path, class: "dropdown-item"
          %li.nav-item
            = link_to "Partenaires", partners_path, class: "nav-link"
          %li.nav-item
            = link_to "Remerciements", thanks_path, class: "nav-link"
      %ul.navbar-nav.d-flex.flex-reverse
        %li.nav-item.dropdown
          %a#navbarDropdown2.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
            = fa_icon "user-circle 4x", class: current_user && "text-warning"
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            - if current_user
              %li
                = link_to "Deconnexion", destroy_user_session_path, method: "DELETE", class: "dropdown-item"
            - else
              %li
                = link_to "Connexion", new_user_session_path, class: "dropdown-item"

app/views/layouts/application.html.haml
!!!
%html.h-100
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EN VOITURE SIMONE
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag image_path('envoituresimone-logo.ico')
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.h-100.d-flex.flex-column
    = render "layouts/navbar"
    - if notice
      .alert.alert-success.mb-0
        = notice
    - if alert
      .alert.alert-danger.mb-0
        = alert
    = yield
    .mt-auto
    = render "layouts/footer"

app/views/partners/_form.html.haml
= form_with model: partner do |f|
  %label Nom
  = f.text_field :name, { class: "form-control mb-3", placeholder: "Super partenaire..." }
  %label Lien vers le site de mon partenaire
  = f.text_field :url, { class: "form-control mb-3", placeholder: "www.site-de-mon-partenaire.com..." }
  %label Logo
  -if f.object.logo.attached?
    .div{ style: "width: 18rem" }
      = image_tag f.object.logo, class: "img-fluid"
    .form-check.form-switch
    = f.check_box :delete_logo, class: "form-check-input", id: "deleteLogo"
    %label.form-check-label{:for => "deleteLogo"} Effacer le logo?
  = f.file_field :logo, { class: "form-control mb-3", accept: 'image/png,image/gif,image/jpeg' }
  = react_component("Ckeditor5", name: "partner[description]", value: partner.description)
  = f.submit partner.new_record? ? "Créer un partenaire" : "Editer le partenaire", { class: "btn btn-success mb-3 w-100"}

app/views/partners/_show.html.haml
.div.position-relative{ style: "width: 18rem" }
  = react_component("Partner", partner: partner.to_react)
  - if current_user
    %a.position-absolute.top-0.end-0.p-1{"data-bs-target" => "#partner-#{partner.id}", "data-bs-toggle" => "modal", :type => "button"}
      = fa_icon "edit 2x"
    .modal.fade{id: "partner-#{partner.id}", "aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-xl
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Edition du partenaire
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            = render 'partners/form', partner: partner
            %button.w-100.ml-auto.btn.btn-warning.mb-3{"data-bs-target" => "#partnerDelete-#{partner.id}", "data-bs-toggle" => "modal", :type => "button"}
              Supprimer le partenaire
            %button.w-100.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Annuler
    .modal.fade{id: "partnerDelete-#{partner.id}", "aria-hidden" => "true", "aria-labelledby" => "editionModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-dialog-centered
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Suppression du partenaire
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            %p.danger La suppression du partenaire est irréversible, êtes-vous sûr de vouloir continuer?
          .modal-footer
            %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Annuler
            = link_to partner_path(partner), method: "DELETE" do
              %button.btn.btn-danger{:type => "button"} Effacer

app/views/partners/index.html.haml
.container.pt-3
  %h1 Partenaires
  %i PARCEQUE C'EST AVEC VOUS QUE NOUS Y ARRIVERONS
  %hr
  - if current_user
    %button.w-100.btn.btn-primary.mb-3{"data-bs-target" => "#articleNew", "data-bs-toggle" => "modal", :type => "button"}
      Ajouter un partenaire
    #articleNew.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-xl
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Ajouter un partenaire
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            = render 'partners/form', partner: Partner.new
  .d-flex.row.justify-content-around
    - @partners.each do |partner|
      = render "show", partner: partner

app/views/rallies/_form.html.haml
= form_with model: @rally do |f|
  = f.text_field :title, { class: "form-control mb-3", placeholder: "Titre..." }
  = react_component("Ckeditor5", name: "rally[presentation]", value: @rally.presentation)
  = f.submit @rally.new_record? ? "Créer un rallye" : "Editer le rallye", { class: "btn btn-success mb-3 w-100"}

app/views/rallies/new.html.haml
.container
  %h1 Nouveau rallye
  = render 'form'

app/views/rallies/show.html.haml
.container.position-relative
  = react_component("Rally", rally: @rally)
  - if current_user
    %a.position-absolute.top-0.end-0.p-1{"data-bs-target" => "#editionModal", "data-bs-toggle" => "modal", :type => "button"}
      = fa_icon "edit 2x"
    #editionModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "editionModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-xl
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Edition du rallye
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            = render 'form', rally: @rally
            %button.w-100.btn.btn-warning.mb-3{"data-bs-target" => "#delteModal", "data-bs-toggle" => "modal", :type => "button"}
              Supprimer le rally
            %button.w-100.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Annuler          
    #delteModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "delteModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-dialog-centered
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Suppression du rallye
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            %p.danger La suppression du rallye est irréversible, êtes-vous sûr de vouloir continuer?
          .modal-footer
            %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Annuler
            = link_to rally_path(@rally), method: "DELETE" do
              %button.btn.btn-danger{:type => "button"} Effacer
  %hr
  %h3.text-center Articles
  - if current_user
    %button.w-100.btn.btn-primary.mb-3{"data-bs-target" => "#articleNew", "data-bs-toggle" => "modal", :type => "button"}
      Créer un article
    #articleNew.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-xl
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Créer un article
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            = render 'articles/form', article: Article.new, rally: @rally

  - @rally.articles.each do |article|
    = render 'articles/show', article: article
    %hr

app/views/statics/home.html.haml
.div
  .fat-hero-image.d-flex.flex-column.justify-content-between.py-2.px-2
    .text-light.d-flex.justify-content-around.h-100.p-5
      %h2 Une histoire de femme et d'aventure,
      %h2.align-self-end pour des rallyes solidaires.
  .bg-hero-image.d-flex.flex-column
    .row.m-0
      .col-sm-6.col-xs-6
        .h-100.d-flex.flex-column.justify-content-center.m-3
          .div
            = image_tag("roses_sables_1.jpg", class: "img-fluid ")
      .col-sm-6.col-xs-6.d-flex.flex-column.justify-content-center
        .bg-transparent-light.p-4.m-4
          %h3
            C'est avec plaisir que nous vous accueillons sur notre site.
          %p
            Nous allons,
            vivre une superbe aventure, avec et grâce à vous,
            mener des actions solidaires ,
            faire de belles rencontres à toutes les étapes.
            Nous avons besoin de vous,
            pour rassembler du matériel destinés aux associations soutenues par le Trophée,
            pour gagner chaque jours des kilomètres qui nous mènerons à l'arrivée du Rallye.
            1€ = 1km
          %strong
            Alors, EN VOITURE SIMONE !
    .container.mt-auto.mb-2
      %hr
      %i
        « Qu’elle ait la peau noire, blanche, jaune ou violette, chaque femme est -devrait être- solidaire de toutes les femmes du monde entier et œuvrer, dans son domaine, sans esprit messianique, pour la justice » 
        %br
        \- Renée Saurel

app/views/thanks/_form.html.haml
= form_with model: thank do |f|
  %label Text
  = react_component("Ckeditor5", name: "thank[content]", value: thank.content)
  = f.submit thank.new_record? ? "Créer un remerciement" : "Editer le remerciement", { class: "btn btn-success mb-3 w-100"}

app/views/thanks/_show.html.haml
.div.position-relative
  = react_component("Thank", thank: thank)
  - if current_user
    %a.position-absolute.top-0.end-0.p-1{"data-bs-target" => "#thank-#{thank.id}", "data-bs-toggle" => "modal", :type => "button"}
      = fa_icon "edit 2x"
    .modal.fade{id: "thank-#{thank.id}", "aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-xl
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Edition du remerciement
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            = render 'form', thank: thank
            %button.w-100.ml-auto.btn.btn-warning.mb-3{"data-bs-target" => "#thankDelete-#{thank.id}", "data-bs-toggle" => "modal", :type => "button"}
              Supprimer le remerciement
            %button.w-100.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Annuler
    .modal.fade{id: "thankDelete-#{thank.id}", "aria-hidden" => "true", "aria-labelledby" => "editionModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-dialog-centered
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Suppression du remerciement
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            %p.danger La suppression du remerciement est irréversible, êtes-vous sûr de vouloir continuer?
          .modal-footer
            %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Annuler
            = link_to thank_path(thank), method: "DELETE" do
              %button.btn.btn-danger{:type => "button"} Effacer

app/views/thanks/index.html.haml
.container.pt-3
  %h1 Remerciements
  %hr
  - if current_user
    %button.w-100.btn.btn-primary.mb-3{"data-bs-target" => "#articleNew", "data-bs-toggle" => "modal", :type => "button"}
      Ajouter un remerciement
    #articleNew.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-xl
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Ajouter un remerciement
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .modal-body
            = render 'form', thank: Thank.new
  .d-flex.row.justify-content-around
    - @thanks.each do |thank|
      = render "show", thank: thank
      %hr.my-2